name: Test - Using Functions for the first time

on:
    pull_request:
    workflow_dispatch:

jobs:
    echo1:
        runs-on: ubuntu-latest
        steps:
            - name: Failed Step
              run: exit 1
            - name: I will be skipped
              if: ${{ success()}}
              run: echo "This step will be skipped because the previous step failed."
            - name: I will execute
              if: ${{ failure()}}
              run: echo "This step will execute because the previous step failed."
            - name: I will execute, except if someone cancels the workflow
              if: ${{ !cancelled()}}
              run: echo "This step will execute because the previous step failed and the workflow was not cancelled."